# @package _global_
# Multi-Agent 2D Navigation environment configuration

# Environment settings
ENV_NAME: multi_agent_nav_v2
ENV_KWARGS:
  num_agents: 4

# Training parameters
NUM_ENVS: 512
NUM_STEPS: 100
TOTAL_TIMESTEPS: 10e7
NUM_MINIBATCHES: 40
LR: 0.0004
MAX_GRAD_NORM: 0.5

# Network architecture
ACTIVATION: tanh
ANNEAL_LR: true

# RL parameters
GAMMA: 0.99
CLIP_EPS: 0.2
ENT_COEF: 0.001

ACTOR_LAYER_SIZES: [256, 256]
CRITIC_LAYER_SIZES: [256, 256]
