# @package _global_
# RAPPO method configuration

ALGORITHM: rappo
# Learning parameters
LR: 0.001
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 25

# RL Algorithm parameters
GAMMA: 0.99
NUM_ENVS: 50
GAE_LAMBDA: 0.95
CLIP_EPS: 0.1
ENT_COEF: 0.0
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
DOMAIN_RANDOMIZATION: false

# Network architecture
ACTIVATION: tanh
ACTOR_LAYER_SIZES: [256, 256]
CRITIC_HIDDEN_SIZE: 32
N_COSINES: 64
N_TAUS: 64
SAMPLE_LB: 0.05
ALPHA: 0.5

# Training settings
ANNEAL_LR: false
NORMALIZE_ENV: true
DEBUG: true
